name: Stage Workflow Actions

on:
  push:
    branches: [main]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'stage-build')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aio1108/12betkhapp
          tags: dev
          buildArgs: DOCKER_ENV=stage
          registry: docker.io
          username: ${{ secrets.STAGE_DOCKER_USERNAME }}
          password: ${{ secrets.STAGE_DOCKER_PASSWORD }}
